# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile

# ---- sora-editor + tm4e (TextMate) ----
# R8 was stripping classes loaded reflectively by the TextMate grammar/theme
# parser, causing ExceptionInInitializerError in the code editor on release.
-keep class io.github.rosemoe.sora.** { *; }
-keep class org.eclipse.tm4e.** { *; }
-keep class org.joni.** { *; }
-keep class org.jcodings.** { *; }
-dontwarn org.eclipse.tm4e.**
-dontwarn org.joni.**
-dontwarn org.jcodings.**

# SnakeYAML (used by tm4e to parse grammar/theme files) relies on reflection.
-keep class org.yaml.snakeyaml.** { *; }
-keepclassmembers class org.yaml.snakeyaml.** { *; }
-dontwarn org.yaml.snakeyaml.**

# Jackson (tm4e parses JSON grammars/themes with it via reflection).
-keep class com.fasterxml.jackson.** { *; }
-keepclassmembers class com.fasterxml.jackson.** { *; }
-dontwarn com.fasterxml.jackson.**

# Attributes needed by the reflection-based parsers above.
-keepattributes Signature,InnerClasses,EnclosingMethod,*Annotation*

# Chaquopy / Python integration
-keep class com.chaquo.python.** { *; }
-dontwarn com.chaquo.python.**

# Auto-generated by R8 (harmless Kotlin stdlib reference in a dependency).
-dontwarn kotlin.Cloneable$DefaultImpls